# RANDOMIZATION
SEED = 121

# DATASET PARAMETRIZATION
# Frames
IMAGE_PAD_RATIO = 0.25
CNN_INPUT_SIZE = 224

# Dataset composition
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15
POS_FRAC_TRAIN = 0.5
POS_FRAC_VAL = 0.5
POS_FRAC_TEST = 0.5


# CLASSIFIER PARAMETRIZATION
BATCH_SIZE = 32
NUM_WORKERS = 4
LEARNING_RATE = 1e-3 * (BATCH_SIZE / 128)
OPTIMIZER_WEIGHT_DECAY = 1e-4
SCHEDULER_REDUCTION_FACTOR = 0.4
SCHEDULER_PATIENCE = 3
USE_AMP = False
EPOCHS = 5
PROB_THRESHOLD = 0.5